stages:
  - test

test_benchmark_runner:
  stage: test

  script:
    - cd benchmark-service
    - ./gradlew clean test

  artifacts:
    when: always
    paths:
      - benchmark-service/build/reports/tests/
    expire_in: 1 week

  tags:
    - gradle

test_webpage_backend:
  stage: test

  script:
    - cd webpage-backend
    - ./gradlew clean test

  artifacts:
    when: always
    paths:
      - webpage-backend/build/reports/tests/
    expire_in: 1 week

  tags:
    - gradle

test_webpage_frontend:
  stage: test

  script:
    - cd webpage-frontend
    - ng test --no-watch --no-progress --browsers=ChromeHeadless

  tags:
    - npm
