stages:
  - test

test_benchmark_runner:
  stage: test
  image: gradle:jdk21

  script:
    - cd /benchmark-service
    - ./gradlew clean test

  artifacts:
    when: always
    paths:
      - /benchmark-service/build/reports/tests/
    expire_in: 1 week

  tags:
    - gradle

test_webpage_backend:
  stage: test
  image: gradle:jdk21

  script:
    - cd /webpage_backend
    - ./gradlew clean test

  artifacts:
    when: always
    paths:
      - /webpage-backend/build/reports/tests/
    expire_in: 1 week

  tags:
    - gradle

