---
configuration:
    name: "My benchmark"
    description: "My benchmark test which instance is better"
    directory: example
    cron: "0 */4 * * *"
    instance-number: 2
    instance-types:
      - t2.micro
      - t3.micro
    instance-tags:
      - - 1 GiB Memory
        - 1 vCPUs
      - - HDD
        - Up to 10 Gigabit Network
nodes:
  - node-id: 0
    ansible-configuration: ansible-0.yaml

  - node-id: 1
    ansible-configuration: ansible-1.yaml
    benchmark-command: ./benchmark-1 > benchmark_output.txt
    output-command: python3 format_output.py benchmark_output.txt
    instance-type: c7gn.16xlarge
    image: ubuntu-with-benchmark-iso

  - node-id: 2
    ansible-configuration: ansible-2.yaml
    benchmark-command: ./benchmark-2 > benchmark_output.txt
    output-command: python3 format_output.py benchmark_output.txt
plots:
  - type: scatter
    title: Example scatter plot
    yaxis: Time [ms]
    series:
      - y: node1InputScalar
        legend: Some name of series
      - y: node2InputScalar
        legend: Some other name
  - type: line
    title: Example line plot
    xaxis: Execution number
    yaxis: Time [ms]
    series:
      - x: increasingNumbers
        y: node1InputScalar
        legend: Some name of series
      - x: someCustomXInput
        y: node2InputScalar
        legend: Some other name
