spring:
  application:
    name: webpage-backend
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@benchmark.7pst8ee.mongodb.net/benchmark-data?retryWrites=true&w=majority
application:
  security:
    bucket:
      size: 40
      refill: 20
    allowed-origin: "https://tumanybenchmarks.netlify.app"
management:
  endpoints:
    web:
      base-path: /