spring:
  application:
    name: benchmark-service
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@benchmark.7pst8ee.mongodb.net/benchmark-data?retryWrites=true&w=majority
aws:
  ec2:
    private-key:
      name: aws-benchmark-private-key
      file-name: aws-benchmark-private-key.pem
    default-ami:
      x86_64: ami-04b70fa74e45c3917
      arm: ami-0eac975a54dfee8cb
    network:
      availability-zone: us-east-1a
      cidr: 10.0.0.0/28
github:
  repository:
    url: https://api.github.com/repos/userName/repositoryName/contents

#logging:
#  level:
#    root: debug