spring:
  application:
    name: benchmark-service
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@benchmark.7pst8ee.mongodb.net/benchmark-data?retryWrites=true&w=majority
aws:
  ec2:
    private-key:
      name: aws-benchmark-private-key
      file: aws-benchmark-private-key.pem
    default-ami:
      x86_64: ami-0bc16b510fa2622db
      arm: ami-0bc16b510fa2622db-arm
    network:
      availability-zone: use1-az1
      cidr: 10.0.0.0/28
github:
  repository:
    url: https://api.github.com/repos/Szczepaniak-M/thesis-test-repo/contents

#logging:
#  level:
#    root: debug