spring:
  application:
    name: benchmark-service
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@benchmark.7pst8ee.mongodb.net/benchmark-data?retryWrites=true&w=majority
#logging:
#  level:
#    root: debug