name: Run Tests
on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test_benchmark_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: Run Benchmark Service Tests
        working-directory: benchmark-service
        run: ./gradlew clean test

      - name: Upload Benchmark Service Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-service-test-report
          path: benchmark-service/build/reports/tests/
          retention-days: 7

  test_webpage_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin

      - name: Run Webpage Backend Tests
        working-directory: webpage-backend
        run: ./gradlew clean test

      - name: Upload Webpage Backend Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: webpage-backend-test-report
          path: webpage-backend/build/reports/tests/
          retention-days: 7

  test_webpage_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: webpage-frontend
        run: npm install

      - name: Install Angular CLI
        working-directory: webpage-frontend
        run: npm install -g @angular/cli

      - name: Run Webpage Frontend Tests
        working-directory: webpage-frontend
        run: ng test --no-watch --no-progress --code-coverage --browsers=ChromeHeadless
